title: Samantha Kuglen

description: >
  Hello and thank you for visiting! <br><br>
  
  I am a marine & environmental Scientist and some of my projects are hyperlinked here. <br>
  I have 6 years of experience at the intersection of conducting oceanographic research and using findings for practical applications. <br>
  - M.S. Environmental Management | UCSB Bren School <br>
  - B.S. Marine Biology | UCSD Scripps Institution of Oceanography <br>
  <br>
  My work has spanned roles working in climate tech, government, and academic research. My ultimate goal is always to translate scientific findings into meaningful applications + actionable outcomes!<br>
  <br>
  <a href="https://samanthakuglen.github.io/portfolio/projects/resume.pdf">View My Resume</a> 

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
google_analytics: UA-000000-0 # Replace with your Google Analytics tracking ID if you have one
