title: Samantha Kuglen

description: >
  Hello and thank you for visiting! <br><br>
  
  I am a Marine & Environmental Scientist with 6 years of experience conducting oceanographic research and using findings for practical applications. <br>
  <br>
  Linked here are a few highlighted projects + community outreach videos.<br>
  <br>
  - M.S. Environmental Management | UCSB Bren School <br>
  - B.S. Marine Biology | UCSD Scripps Institution of Oceanography <br>
  <br>
  Currently, I work in environmental compliance documentation. I have previously held roles in climate tech, government, and academic research. My ultimate goal is always to translate scientific findings into meaningful, actionable outcomes!<br>
  <br>
  <a href="https://samanthakuglen.github.io/portfolio/projects/resume.pdf">View My Resume</a> 

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
google_analytics: UA-000000-0 # Replace with your Google Analytics tracking ID if you have one
